FROM mcr.microsoft.com/mssql/server:2022-latest

# No necesitas instalar mssql-tools manualmente, ya vienen incluidos
USER root

# Solo asegura los permisos adecuados
RUN mkdir -p /var/opt/mssql/data && \
    chown -R mssql /var/opt/mssql

USER mssql

EXPOSE 1433
CMD ["/opt/mssql/bin/sqlservr"]